language: node_js
node_js:
  - 12
cache:
  npm: false
  directories:
    - $HOME/.npm
env:
  - CI=true
  - BUILD_PATH='./docs'
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
  
  